#docker-compose.yml
version: "3.8"
services:

  service-super-market:
    build: ./service-super-market
    image: pzoani/service-super-market
    ports:
      - 9090:8080
    environment:
      - SERVER_PORT=8080
      - MONGO_HOST=db
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    depends_on:
      - db

  db:
    image: mongo:4.4.1
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ${MONGO_VOLUME_PATH}:/data/db
