spring:
  application:
    name: service-super-market
  output:
    ansi:
      enabled: always
  main:
    banner-mode: off
  profiles:
    active:
      - bootstrap
      - controllers # controllers | handlers
      - localhost-OS # localhost-OS | docker
logging:
  level:
    root: INFO
---
spring:
  profiles: docker
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: 27017
      database: ${MONGO_DB_NAME}
server:
  port: 8080
---
spring:
  profiles: localhost-OS
  data:
    mongodb:
      host: localhost
      port: 27017
      database: super-market
server:
  port: 8080