logging:
  level:
    root: INFO
server:
  port: 8080
spring:
  application:
    name: service-super-market
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
  profiles:
    active:
      - bootstrap
      - controllers # controllers | handlers
      - embed-mongo # localhost-OS | docker | embed-mongo
---
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  profiles: docker
  data:
    mongodb:
      database: ${MONGO_DB_NAME}
      host: ${MONGO_HOST}
      port: 27017
---
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  profiles: localhost-OS
  data:
    mongodb:
      database: super-market
      host: localhost
      port: 27017
---
spring:
  profiles: embed-mongo
  data:
    mongodb:
      database: super-market